version: "3"

services:
  db:
    image: docker.io/library/postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pastel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastel
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - pastelnet
  be:
    image: andreagast/pastel
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: pastel
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: pastel
    networks:
      - pastelnet

  fe:
    image: andreagast/pastel-fe
    build: ./frontend
    networks:
      - pastelnet
  lb:
    image: docker.io/library/nginx:alpine
    depends_on:
      - be
      - fe
    ports:
      - "8080:80"
    volumes:
      - ./confs/nginx-lb.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pastelnet


networks:
  pastelnet: {}

volumes:
  db-data: {}
